In [2]:
## 1. Split this string
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


In [102]:
## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
planet = "Earth"
diameter = 12742
print("The diameter of {0} is {1} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


In [76]:
## 3. In this nest dictionary grab the word "hello"
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a = d['k1']
b = a[3]
c = b['tricky']
d = c[3]
e = d['target'][3]
print(e)

hello


In [81]:
import numpy as np
##4.1 Create an array of 10 zeros? 
arr = np.zeros(10)

print(arr)
## 4.2 Create an array of 10 fives?
arr = np.ones(10)*5
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [38]:
## 5. Create an array of all the even integers from 20 to 35
arr =np.array([i for i in range(20,36) if(i%2 ==0) ])
print(np.array(arr))

[20 22 24 26 28 30 32 34]


In [61]:
## 6. Create a 3x3 matrix with values ranging from 0 to 8
arr = np.array([range(0,9)])
print(arr.reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [84]:
## 7. Concatenate a and b 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b),axis =0)
print(c)

[1 2 3 4 5 6]


In [96]:
## 8. Create a dataframe with 3 rows and 2 columns
import pandas as pd
data = [[1,2],[4,5],[6,7]]
df = pd.DataFrame(data,columns=['a','b'])
print(df)

   a  b
0  1  2
1  4  5
2  6  7


In [101]:
## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023
min_date = "2023-01-01"
max_date ="2023-02-10"
dt = pd.date_range(min_date,max_date)
dt

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [39]:
## 10. Create 2D list to DataFrame
import pandas as pd
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
